---
image: ubuntu:latest

services:
  - docker:dind

before_script:
  - apt-get -yq update
  - apt-get -yq install python-minimal python2.7 python2.7-dev python3.6 python3.6-dev python3.7 python3.7-dev python-pip
  - apt-get -yq git
  - pip install tox
  - docker -v
  - python -V
  - ansible --version
  - molecule --version

stages:
  - tox

tox:
  stage: tox
  script:
    - tox -e py27-ansible27 -- molecule test -s default
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
