---

- name: create the Trickster systemd service file
  template:
    src: trickster.service.j2
    dest: /etc/systemd/system/trickster.service
    owner: root
    group: root
    mode: 0644
  notify: restart trickster

- name: create Trickster config
  template:
    src: trickster.j2
    dest: "{{ sysconfig_directory }}/trickster"

- name: create Trickster config for systemd unit file
  template:
    src: trickster.conf.j2
    dest: /etc/trickster
