---

- name: create the trickster systemd service file
  template:
    src: systemd/trickster.service.j2
    dest: "{{ systemd_lib_directory }}/trickster.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload
    - restart trickster

- name: create trickster config
  template:
    src: trickster.j2
    dest: "{{ sysconfig_directory }}/trickster"
    mode: 0644
  notify:
    - restart trickster

- name: create trickster config for systemd unit file
  template:
    src: trickster.conf.j2
    dest: "{{ trickster_service_config.config_file }}"
    mode: 0644
  notify:
    - restart trickster

...
