---

- name: create the Trickster systemd service file
  template:
    src: systemd/trickster.service.j2
    dest: "{{ systemd_lib_directory }}/trickster.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload

- name: create Trickster config
  template:
    src: trickster.j2
    dest: "{{ sysconfig_directory }}/trickster"
    mode: 0644

- name: create Trickster config for systemd unit file
  template:
    src: trickster.conf.j2
    dest: "{{ trickster_service_config.config_file }}"
    mode: 0644
...
