---

- name: detect binary file for trickster
  become: false
  delegate_to: "{{ trickster_delegate_to }}"
  run_once: "{{ 'false' if trickster_direct_download else 'true' }}"
  stat:
    path: "{{ trickster_local_tmp_directory }}/trickster-{{ trickster_version }}/bin/trickster-{{ trickster_version }}.linux-{{ go_arch }}"
  register: stat_file_binary


- name: propagate files
  block:
    - name: propagate trickster binaries
      copy:
        src: "{{ trickster_local_tmp_directory }}/trickster-{{ trickster_version }}/bin/trickster-{{ trickster_version }}.linux-{{ go_arch }}"
        dest: "{{ trickster_install_path }}/trickster"
        mode: 0755
        owner: "{{ trickster_system_user }}"
        group: "{{ trickster_system_group }}"
        remote_src: "{{ 'true' if trickster_direct_download else 'false' }}"
      notify:
        - reload trickster
  when:
    - stat_file_binary.stat.exists

- name: create local facts
  template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/trickster.fact
    mode: 0755

- name: create link to binary
  file:
    src: "{{ trickster_install_path }}/trickster"
    dest: /usr/bin/trickster
    state: link
    force: true
  notify:
    - restart trickster

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create trickster config for systemd unit file
      template:
        src: trickster.conf.j2
        dest: "{{ trickster_service_config.config_file }}"
        mode: 0644
      notify:
        - restart trickster

    - name: create the trickster systemd service file
      template:
        src: init/systemd/trickster.service.j2
        dest: "{{ systemd_lib_directory }}/trickster.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart trickster

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      template:
        src: "init/openrc/conf.d/trickster.j2"
        dest: "/etc/conf.d/trickster"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      template:
        src: "init/openrc/init.d/trickster.j2"
        dest: "/etc/init.d/trickster"
        owner: root
        group: root
        mode: 0750

...
