---

- name: propagate trickster
  copy:
    src: "{{ trickster_local_tmp_directory }}/trickster-{{ trickster_version }}/bin/trickster-{{ trickster_version }}.linux-{{ go_arch }}"
    dest: "/usr/local/bin/trickster"
    mode: 0755
    owner: root
    group: root
  notify:
    - restart trickster
