---

- name: detect binary file for trickster
  become: false
  delegate_to: "{{ trickster_delegate_to }}"
  run_once: "{{ 'false' if trickster_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ trickster_local_tmp_directory }}/trickster-{{ trickster_version }}/bin/trickster-{{ trickster_version }}.linux-{{ go_arch }}"
  register: stat_file_binary

- name: propagate trickster binaries
  ansible.builtin.copy:
    src: "{{ trickster_local_tmp_directory }}/trickster-{{ trickster_version }}/bin/trickster-{{ trickster_version }}.linux-{{ go_arch }}"
    dest: "{{ trickster_install_path }}/trickster"
    mode: 0755
    owner: "{{ trickster_system_user }}"
    group: "{{ trickster_system_group }}"
    remote_src: "{{ 'true' if trickster_direct_download else 'false' }}"
  when:
    - stat_file_binary.stat.exists
  notify:
    - reload trickster

- name: create custom fact file
  bodsch.core.facts:
    name: trickster
    facts:
      version: "{{ trickster_version }}"

- name: create link to binary
  ansible.builtin.file:
    src: "{{ trickster_install_path }}/trickster"
    dest: /usr/bin/trickster
    state: link
    force: true
  notify:
    - restart trickster

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create trickster run configuration
      ansible.builtin.template:
        src: trickster.j2
        dest: "{{ trickster_defaults_directory }}/trickster"
        mode: 0644
      notify:
        - restart trickster

    - name: create systemd service unit
      ansible.builtin.template:
        src: init/systemd/trickster.service.j2
        dest: "{{ systemd_lib_directory }}/trickster.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart trickster

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/trickster.j2"
        dest: "/etc/conf.d/trickster"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/trickster.j2"
        dest: "/etc/init.d/trickster"
        owner: root
        group: root
        mode: 0750

...
