---

# - name: Gather variables for each operating system
#   include_vars: "{{ item }}"
#   with_first_found:
#     - "{{ ansible_distribution_file_variety | lower }}.yml"
#     - "{{ ansible_distribution | lower }}.yml"
#     - "{{ ansible_os_family | lower }}.yml"
#   tags:
#     - trickster_install
#     - trickster_configure
#     - trickster_run

- import_tasks: prepare.yml
  tags:
    - trickster_install
    - trickster_configure
    - trickster_run

- import_tasks: download.yml
  become: true
  tags:
    - trickster_install

- import_tasks: install.yml
  become: true
  tags:
    - trickster_install

- import_tasks: configure.yml
  become: true
  tags:
    - trickster_configure

# - import_tasks: service.yml
#   become: true
#   tags:
#     - trickster_run
#     - trickster_configure

...
