---

- import_tasks: prepare.yml
  tags:
    - trickster_install
    - trickster_configure
    - trickster_run

- import_tasks: download.yml
  become: true
  tags:
    - trickster_install

- import_tasks: install.yml
  become: true
  tags:
    - trickster_install

- import_tasks: configure.yml
  become: true
  tags:
    - trickster_configure

- import_tasks: service.yml
  become: true
  tags:
    - trickster_run
    - trickster_configure

...
