---

- name: Ensure trickster is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: trickster
    enabled: true
    state: started
  tags:
    - trickster_run

...
