---
- name: prepare container
  hosts: all
  gather_facts: true

  pre_tasks:

    - debug:
        msg:
          - "OS family       {{ ansible_os_family }}"
          - "distribution    {{ ansible_distribution }}"
          - "major version   {{ ansible_distribution_major_version }}"
          - "version         {{ ansible_distribution_version }}"
          - "ansible_version {{ ansible_version.full }}"
          - "python version  {{ ansible_python.version.major }}"
