---

- name: prometheus
  src: https://github.com/cloudalchemy/ansible-prometheus.git
  scm: git
  version: 4.0.0

- name: redis
  src: https://github.com/bodsch/ansible-redis.git
  scm: git
  version: 1.1.1

...
