---

- name: prometheus
  src: https://github.com/bodsch/ansible-prometheus.git
  scm: git
  version: 1.0.1

- name: redis
  src: https://github.com/bodsch/ansible-redis.git
  scm: git
  version: 1.1.1

...
